version: '2'
services:
    rethinkdbjhipster-app:
        image: rethinkdbjhipster
        external_links:
            - rethinkdbjhipster-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=rethinkdbjhipster
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    rethinkdbjhipster-mongodb:
        extends:
            file: mongodb.yml
            service: rethinkdbjhipster-mongodb
