version: '2'
services:
    rethinkdbjhipster-sonar:
        container_name: rethinkdbjhipster-sonar
        image: sonarqube:5.6.1-alpine
        ports:
            - 9000:9000
            - 9092:9092
